### ISSUE TITLE
 meta-somlabs 'zeus' build issue with 'imx-linux-zeus' 

### ISSUE THREAD

**Issue by rhardik** [SoMLabs/imx-meta-somlabs#1]
I am following README for yocto setup but the compilation doesn't work for the latest meta-somlabs commit.

Then I followed somlab.vbox  and according to that checked out to the meta-somlabs commit 0e0695d281cef (SOMLABS: update the kernel commit).

Now compilation works with 'meta-somlabs' commit 0e0695d281cef  and 'imx-linux-zeus'.

So should we solve the 'zeus' compatibility issues with imx-linux-zeus' or just have a release/tag for  commit 0e0695d281cef ?

Thanks,
Hardik
Embdes Engineering Solutions Pvt Ltd

**Comment by kchojnowski** [comment]
Hi,

thanks for letting know about the problem. Could you please give more details about the issue and paste some console logs?

Regards,
Krzysztof

**Comment by rhardik** [comment]
Hi Krzysztof,

Error screenshot
![Screenshot from 2020-12-28 17-19-50](https://user-images.githubusercontent.com/7348046/103212784-d6bf0480-4931-11eb-94f9-4203144226ae.png)

meta-somlab commit screenshot
![Screenshot from 2020-12-28 17-23-12](https://user-images.githubusercontent.com/7348046/103213196-f571cb00-4932-11eb-943a-96c5871bedf6.png)

poky commit screenshot
![Screenshot from 2020-12-28 17-23-40](https://user-images.githubusercontent.com/7348046/103213358-729d4000-4933-11eb-955f-89794e029ead.png)


As shown in below screenshot  imx-atf_2.0.bb and imx-atf_2.2.bbappend version not matching.
![Screenshot from 2020-12-28 17-20-51](https://user-images.githubusercontent.com/7348046/103213217-04587d80-4933-11eb-8058-d3ec4608df15.png)

Thanks,
Hardik
Embdes Engineering Solutions Pvt Ltd (e2-s)

**Comment by kchojnowski** [comment]
Hi Hardik,

I can see that you have some version mismatch, because you should see the imx-atf version 2.2 in your meta-imx layer. Did you checked out zeus version imx-5.4.24? You should update the imx project according to the imx-5.4.24-2.1.0.xml file. Please check the last version of README file in meta-somlabs. You may need to do a clean project checkout and build step-by-step as in mentioned file.

Regards,
Krzysztof

**Comment by rhardik** [comment]
Hi  Krzysztof,

 The build working fine for the old commit 0e0695d in _meta-somlabs_.

I should close this issue here and open the same in _meta-somlabs_ repository.

Thanks,
Hardik
Embdes Engineering Solutions Pvt Ltd (e2-s)

**Comment by kchojnowski** [comment]
Hi,

I works because in the commit you mentioned older version of imx bsp (5.4.3) is used. If you updated the meta-somlabs to the newest version, you also need to update the imx meta-layer to 5.4.24. Please check the version numbers in meta-somlabs README.

Regards,
Krzysztof

**Comment by rhardik** [comment]
Hi  Krzysztof,

Yes It's working after upgrading to 5.4.24.

Actually I was following a webinar video where imx-5.4.3-2.0.0.xml and 'zeus' branch for meta-somlabs are used.
but since then zeus got updated.

Thanks for your support, Issue is resolved now and also I have learned about xml files to maintain versions :)

Thank you,
Hardik
